#!/usr/bin/env python3
"""Generate the wiki command reference from osm's own argparse definitions.

Walks the parser tree built by `os_manager.cli.build_parser` and writes one
markdown page describing every command, subcommand, argument and flag. Run by
the `wiki` GitHub Action, so the reference cannot drift from the code.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from os_manager.cli import build_parser  # noqa: E402

PAGE = "Command-Reference.md"

PREAMBLE = """<!-- Generated by tools/gen_command_reference.py. Do not edit by hand:
     edits are overwritten on the next push to the default branch. -->

# Command reference

Every command, argument and flag `osm` accepts, generated from the source.

An unrecognised first word is not an error: it is sent to the OpenSearch REST
API as a path, with `cluster`, `cat` and `nodes` expanded to `_cluster`, `_cat`
and `_nodes`.

```bash
osm _cluster/health
osm cat indices
osm -t prod cat shards
```

Listing commands accept `--json`. Export commands write ndjson to stdout, a
JSON array under `--json`, or one file per object under `--to-file [DIR]`.
Import commands take several files and expand wildcards themselves, so quoted
patterns work.
"""


def is_subparsers(action):
    return isinstance(action, argparse._SubParsersAction)


def subparsers_of(parser):
    """The (name, parser, summary) triples one level below `parser`.

    The summary is the `help=` given to `add_parser`, which argparse keeps on a
    pseudo-action rather than on the subparser itself.
    """
    for action in parser._actions:
        if not is_subparsers(action):
            continue
        summaries = {a.dest: (a.help or "") for a in action._choices_actions}
        return [(name, sub, summaries.get(name, ""))
                for name, sub in action.choices.items()]
    return []


def escape(text):
    """Markdown table cells cannot hold a raw pipe."""
    return text.replace("|", "\\|")


def metavar_of(action):
    if action.metavar:
        return action.metavar
    if action.choices:
        return "{" + "|".join(str(choice) for choice in action.choices) + "}"
    return action.dest.upper() if action.option_strings else action.dest


def placeholder(action):
    """How the argument's value appears in the invocation column."""
    if action.nargs == 0:
        return ""
    metavar = metavar_of(action)
    if isinstance(metavar, tuple):
        return " ".join(metavar)
    if action.nargs == "?":
        return f"[{metavar}]"
    if action.nargs == "*":
        return f"[{metavar} ...]"
    if action.nargs == "+":
        return f"{metavar} [{metavar} ...]"
    if isinstance(action.nargs, int):
        return " ".join([metavar] * action.nargs)
    return metavar


def invocation(action):
    value = escape(placeholder(action))
    if not action.option_strings:
        return f"`{value}`"
    flags = ", ".join(f"`{flag}`" for flag in action.option_strings)
    return f"{flags} `{value}`" if value else flags


def describe(action):
    parts = [(action.help or "").strip()]
    if action.required and action.option_strings:
        parts.append("required")
    return escape(". ".join(part for part in parts if part)) or "-"


def documented(parser):
    """Arguments worth listing: everything except --help and the subcommand slot."""
    for action in parser._actions:
        if is_subparsers(action) or isinstance(action, argparse._HelpAction):
            continue
        if action.help == argparse.SUPPRESS:
            continue
        yield action


def usage_of(parser):
    """`parser.format_usage()` on one line, without "usage: " or the -h noise."""
    usage = " ".join(parser.format_usage().split())[len("usage: "):]
    return usage.replace(" [-h]", "", 1)


def argument_table(parser):
    actions = list(documented(parser))
    if not actions:
        return []
    lines = ["| Argument | Description |", "|---|---|"]
    lines += [f"| {invocation(a)} | {describe(a)} |" for a in actions]
    return lines + [""]


def anchor(name):
    return "#" + name.replace(" ", "-")


def render_command(name, parser, summary, depth, lines):
    lines.append(f"{'#' * depth} `{name}`")
    lines.append("")
    for text in (summary, parser.description, parser.epilog):
        if text:
            lines.append(" ".join(text.split()))
            lines.append("")

    children = subparsers_of(parser)
    if children:
        for child_name, _, child_summary in children:
            full = f"{name} {child_name}"
            lines.append(f"- [`{full}`]({anchor(full)})"
                         + (f" - {child_summary}" if child_summary else ""))
        lines.append("")
    else:
        lines.append("```")
        lines.append(usage_of(parser))
        lines.append("```")
        lines.append("")
    lines += argument_table(parser)

    for child_name, child, child_summary in children:
        render_command(f"{name} {child_name}", child, child_summary, depth + 1, lines)


def toc(parser):
    """A nested bullet list of every command, down to the leaves."""
    lines = []

    def walk(name, sub, summary, indent):
        lines.append(f"{'  ' * indent}- [`{name}`]({anchor(name)})"
                     + (f" - {summary}" if summary else ""))
        for child_name, child, child_summary in subparsers_of(sub):
            walk(f"{name} {child_name}", child, child_summary, indent + 1)

    for name, sub, summary in subparsers_of(parser):
        walk(f"osm {name}", sub, summary, 0)
    return lines + [""]


def render(parser):
    lines = [PREAMBLE, "## Global options", "",
             "These come before the command, and apply to raw REST paths too.", ""]
    lines += argument_table(parser)

    lines += ["## Commands", ""] + toc(parser)

    for name, child, summary in subparsers_of(parser):
        render_command(f"osm {name}", child, summary, 2, lines)

    return "\n".join(lines).rstrip() + "\n"


def main():
    argv = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    argv.add_argument("outdir", nargs="?", default="docs/wiki",
                      help="directory to write %s into (default: docs/wiki)" % PAGE)
    argv.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = argv.parse_args()

    content = render(build_parser())
    if args.stdout:
        print(content, end="")
        return 0
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / PAGE).write_text(content)
    print(f"wrote {out / PAGE} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
